try {
	test();
} catch (error) {
	console.log(error);
} finally {
	console.log('finally!');
}